### ISSUE TITLE
bug: Not removing all vestigial nodes from the building

### ISSUE THREAD

**Issue by Pantyhose-X** [bell07/minetest-townchest#2]
Flatting and cleanup the building schematic place, remove all cruft-nodes from building schematic inside

* use ABM and LBM. Remove all nodes from the schematic location
* Start Build

**Comment by bell07** [comment]
If I understand your issue, this is by design. By default all air nodes in schematic are ignored. Before you start the build, you can use the "Flood with air" button to get all vestigal nodes removed from building by replacing with air.
Let me know if I understand right your issue.

**Comment by Pantyhose-X** [comment]
npc build No Fill with air used

**Comment by bell07** [comment]
NPC build is compatible with fill air. Then the NPC removes the not used items (place air) ;-)

**Comment by Pantyhose-X** [comment]
Problem solved
npc too slow, suggest to modify the speed
Suggested uploads to contentDB

closed this as completed

**Comment by bell07** [comment]
> npc too slow, suggest to modify the speed

Suggest to spawn more NPC's ;-)
